using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ContosoUniversity.Models;
using Microsoft.EntityFrameworkCore;
using ContosoUniversity.Data;
using ContosoUniversity.Models.SchoolViewModels;
using System.Data.Common;

namespace ContosoUniversity.Controllers
{
    public class HomeController : Controller
    {
        private readonly SchoolContext _context;

        public HomeController(SchoolContext context)
        {
            _context = context;
        }

        /*
         * An about method that returns the number of students per enrollment date (e.g. 5 students enrolled on 9/2005)
         * Updated to use raw SQL queries vs. LINQ
         */
        public async Task<ActionResult> About()
        {
            // Create a collection to store what will be passed to the view
            List<EnrollmentDateGroup> groups = new List<EnrollmentDateGroup>();
            // Open the connection with our DB
            var conn = _context.Database.GetDbConnection();
            try
            {
                await conn.OpenAsync();
                // Generate a command to pass to our DB. 
                using (var command = conn.CreateCommand())
                {
                    // Create the equivalent SQL statement to count all students stored within the DB
                    string query = "SELECT EnrollmentDate, COUNT(*) AS StudentCount "
                        + "FROM Person "
                        + "WHERE Discriminator = 'Student' "
                        + "GROUP BY EnrollmentDate";
                    // set the commands query text to the string we generated
                    command.CommandText = query;
                    // Pass the stream generated by our command to the reader for processing
                    DbDataReader reader = await command.ExecuteReaderAsync();

                    if (reader.HasRows)
                    {
                        while (await reader.ReadAsync())
                        {
                            // Give values to our wrapper model from the rows we retrieved from the DB.
                            var row = new EnrollmentDateGroup { EnrollmentDate = reader.GetDateTime(0) /* Grab from the first col*/, StudentCount = reader.GetInt32(1) /* Grab from 2nd col*/};
                            // When we're done, add it to our collection being passed to the view.
                            groups.Add(row);
                        }
                    }
                    // free up all the resources our reader was allocated
                    reader.Dispose();
                }
            }
            // Close our connections (we're done retreiving) 
            finally
            {
                conn.Close();
            }
            return View(groups);
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}


